### ISSUE TITLE
It don't start the loader

### ISSUE THREAD

**Issue by Vasilis553** [TheEntropyShard/PTLauncher#1]
The client opens to select profile opens but when I press play the window just restarts without the loader start

**Comment by TheEntropyShard** [comment]
Can you provide logs?

**Comment by Vasilis553** [comment]
![Uploading Screenshot_2024-04-19-18-24-55-301_com.miui.gallery.jpg…]()

**Comment by Vasilis553** [comment]
It say this each time I press play and just refreshes the first screen

**Comment by TheEntropyShard** [comment]
The link is broken

**Comment by Vasilis553** [comment]
https://prnt.sc/Lh4EhEi4WxTV

**Comment by TheEntropyShard** [comment]
Did you build the project yourself?

**Comment by Vasilis553** [comment]
No I got it ready I tried to build bcz I was not able to build it

**Comment by TheEntropyShard** [comment]
You probably got an old jar which does not have the bugfix, but here is jar that I built for you. Unpack the archive, it contains the jar.
[ptlauncher-1.0-jar-with-dependencies.zip](https://github.com/TheEntropyShard/PTLauncher/files/15042789/ptlauncher-1.0-jar-with-dependencies.zip)

**Comment by Vasilis553** [comment]
Thanks a lot I will check in few hours that I'll return home!!

**Comment by TheEntropyShard** [comment]
No problem :)

**Comment by Vasilis553** [comment]
Closed!
Thank you very much Entropy!

**Comment by Vasilis553** [comment]
Is any way to make it recognize locale en?

**Comment by TheEntropyShard** [comment]
Oh :D Here is the jar with english locale. I did not make any language switch and this project is kinda abandoned.
[ptlauncher-1.0-jar-with-dependencies.jar.zip](https://github.com/TheEntropyShard/PTLauncher/files/15111998/ptlauncher-1.0-jar-with-dependencies.jar.zip)
