### ISSUE TITLE
launcher just doesnt work

### ISSUE THREAD

**Issue by FatalDiscovery** [TheEntropyShard/PTLauncher#2]
it just doesnt open, it does on my old pc but on my new one it doesnt. i think its a java problem but i changed the version i use and nothing happens. profiles.json doesnt change anything when i change it. theres no pro tanki folder created in appdata either
![Animation-ezgif com-optimize](https://github.com/TheEntropyShard/PTLauncher/assets/157039155/086462c0-a76a-45ff-b787-c29653b045fb)

**Comment by TheEntropyShard** [comment]
How did acquire the launcher jar? Did you build it yourself or somebody sent it to you?

**Comment by FatalDiscovery** [comment]
i built it my self

**Comment by TheEntropyShard** [comment]
Hmmm. Can you show the log of the launcher? Does it print any errors?

**Comment by FatalDiscovery** [comment]
![image](https://github.com/TheEntropyShard/PTLauncher/assets/157039155/1db8aae5-293d-43c9-b5fb-0232448b0d07)
theres nothing

**Comment by TheEntropyShard** [comment]
Can you try this? https://github.com/TheEntropyShard/PTLauncher/files/15111998/ptlauncher-1.0-jar-with-dependencies.jar.zip

**Comment by FatalDiscovery** [comment]
nope, same thing 😢

**Comment by FatalDiscovery** [comment]
Good news i have fixed the problem :D.  It was not your launcher that was faulty. Basically i installed Windows 11 N which is windows without like windows media player and other windows software. It also comes with some .dll files missing which can cause some errors.
The way to fix it is to place this .dll in the root folder of the air runtime the app uses.
Here's the file if anyone else is having this error: https://github.com/airsdk/Adobe-Runtime-Support/files/8253919/dsound.zip
